package model;
// Generated May 15, 2021, 11:06:35 AM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * UserLink generated by hbm2java
 */
public class UserLink implements java.io.Serializable {

	private int id;
	private Link link;
	private Users users;
	private String url;
	private int activeFlag;
	private Date createDate;
	private Date updateDate;

	public UserLink() {
	}

	public UserLink(int id, Link link, Users users, String url, int activeFlag, Date createDate, Date updateDate) {
		this.id = id;
		this.link = link;
		this.users = users;
		this.url = url;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Link getLink() {
		return this.link;
	}

	public void setLink(Link link) {
		this.link = link;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
