package inventory.model;
// Generated May 15, 2021, 11:06:35 AM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Link generated by hbm2java
 */
public class Link implements java.io.Serializable {

	private Integer id;
	private String name;
	private int activeFlag;
	private Date createDate;
	private Date updateDate;
	private Set userLinks = new HashSet(0);

	public Link() {
	}

	public Link(String name, int activeFlag, Date createDate, Date updateDate) {
		this.name = name;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Link(String name, int activeFlag, Date createDate, Date updateDate, Set userLinks) {
		this.name = name;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.userLinks = userLinks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Set getUserLinks() {
		return this.userLinks;
	}

	public void setUserLinks(Set userLinks) {
		this.userLinks = userLinks;
	}

}
